### ISSUE TITLE
Failing to load driver on Raspberry Pi Zero W, dirty close

### ISSUE THREAD

**Issue by juhalehtonen** [pappersverk/scenic_driver_inky#3]
First of all, apologies for the relatively vague issue. I'm not completely sure what's causing the problems I'm facing, so I wasn't sure how to group or name the issue(s).

## What I'm attempting to do

I tried to follow http://underjord.io/an-eink-display-with-nerves-elixir.html to get Scenic to run on my Raspberry Zero W. I also tried to clone https://github.com/lawik/tutorial_eink directly and only changed the SSH config in order to ensure I wasn't making any errors in replicating the code.

## What I'm expecting to happen

Scenic should load and display the "My name is.." sample scene.

## What really happens

Depending on whether I'm testing with Elixir 1.9/OTP22 with latest Nerves Bootstrap (1.6) or Elixir 1.8/OTP21 with downgraded Nerves Bootstrap (1.5), one of two things happens:

### 1) On the 1.9 setup
I get the checkers pattern to show up on the display (as per the sample code), but nothing more. SSH'ing to the Raspberry Pi and looking at the logs returns the following:

```elixir
00:00:52.489 [error] Jan  1 00:00:52 rpi_fb_capture: Unable to open primary display

00:00:52.496 [error] GenServer #PID<0.1566.0> terminating
** (stop) bad return value: {:stop, :port_crashed}
Last message: {#Port<0.187>, {:exit_status, 1}}
State: %RpiFbCapture.State{display_height: 0, display_id: 0, display_width: 0, height: 104, port: #Port<0.187>, request: {{#PID<0.1563.0>, #Reference<0.1665486460.268435457.243310>}, :rgb24}, width: 212}

00:00:52.503 [error] GenServer #PID<0.1563.0> terminating
** (MatchError) no match of right hand side value: {:error, :port_crashed}
    (scenic_driver_inky) lib/scenic_driver_inky.ex:90: ScenicDriverInky.handle_info/2
    (scenic) lib/scenic/view_port/driver.ex:215: Scenic.ViewPort.Driver.handle_info/2
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: :capture
State: %{driver_module: ScenicDriverInky, driver_state: %{cap: #PID<0.1566.0>, color_affinity: :low, color_high: 180, color_low: 75, dithering: false, inky_pid: #PID<0.1565.0>, interval: 1000, last_crc: -1, size: {212, 104}, viewport: #PID<0.1548.0>}, viewport: #PID<0.1548.0>}

00:00:52.512 [error] GenServer #PID<0.1564.0> terminating
** (stop) bad return value: {:stop, :port_crashed}
Last message: {:EXIT, #PID<0.1563.0>, {:bad_return_value, {:stop, :port_crashed}}}
State: %{driver_module: Scenic.Driver.Nerves.Rpi, driver_state: %{clear_color: {0, 0, 0, 255}, closing: false, currently_drawing: [], debounce: %{}, dirty_graphs: [], dl_block_size: 128, dl_map: %{}, draw_busy: false, end_dl: nil, fonts: %{}, inputs: 0, last_used_dl: nil, pending_flush: false, port: #Port<0.186>, ready: false, root_ref: nil, screen_factor: 1.0, start_dl: nil, sync_interval: 15, textures: %{}, used_dls: %{}, viewport: #PID<0.1548.0>}, viewport: #PID<0.1548.0>}

00:00:52.539 [error] dirty close
```

### 2) On the 1.8 setup
I get past the checkers pattern and the Raspberry logo loads up on a black background, but the Scenic scene doesn't show up. SSH'ing into the Raspberry Pi and checking the logs returns the following:

```
00:00:45.888 [error] dirty close
```

## Context

I exchanged some emails with @lawik , and he proposed that I could have a minimal test case for the 1.9 error via the following:

```elixir
{:ok, cap} = RpiFbCapture.start_link(width: width, height: height, display: 0)
{:ok, frame} = RpiFbCapture.capture(cap, :rgb24)
```

Indeed, running this returns an error on the 1.9/OTP22 setup but works fine with the 1.8/OTP21 setup.

### Development environment
Macbook Pro running on macOS Mojave 10.14.5

### Hardware
- Raspberry Pi Zero W
- Inky Phat Red

**Comment by juhalehtonen** [comment]
I tested this once more with a different set of versions, and actually managed to get things working.

What worked for me was setting Elixir to 1.8.2 OTP 21, and Nerves Bootstrap to 1.5.2.

**Comment by lawik** [comment]
Thanks. This is really good to know. I've poked the repo for RpiFbCapture about it. I'll follow up with @fhunleth over there.

**Comment by fhunleth** [comment]
FYI: I fixed the port crash. I did see the “dirty close” log from scenic, but it magically disappeared on a clean build for me. I’m going to try to get official Nerves systems out in the next few days with the fix to the RPI firmware.

**Comment by lawik** [comment]
I'll keep an eye out for the release and close this when I can verify it on the new release.
Good job :)

**Comment by fhunleth** [comment]
The 1.8.2 release is out. Could you see if it works better? https://github.com/nerves-project/nerves_system_rpi0/releases/tag/v1.8.2

**Comment by lawik** [comment]
I'm just about to head out on a vacation trip, so I won't have the chance for 3 weeks. Hopefully @juhalehtonen or @nyaray can verify it. Otherwise I'll get to it when I get back.

**Comment by fhunleth** [comment]
FYI - I just tried this out again and while I'm no longer getting the rpi_fb_capture crashes, I am getting the "dirty close". I think that the "dirty close" error is unrelated to the rpi_fb_capture issue. I haven't looked into it, so I'm not sure why it sometimes happens and sometimes doesn't for me.

**Comment by lawik** [comment]
This seems to have resolved the issue. Closing :)
